#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org 

START=11

. /lib/functions.sh

set_timezone_from_countrycode() {
	local cc=`getCountryCode`

	if [ -z "$cc" ]; then
        	tz="UTC"
	else
        	tz=`uci -q get country_mapping.$cc.timezone`
		tz_idx=$(uci -q get country_mapping.$cc.timezoneindex)
        	[ -z "$tz" ] && tz="UTC"
	fi

	echo $tz > /tmp/TZ
	# update uci config. config_set doesn't work >_<
	# config_set $1 timezone $tz
	uci set system.@system[0].timezone="$tz"
	uci set system.@system[0].timezoneindex="$tz_idx"
	uci commit system
}


timezone_config() {
	local cfg="$1"
	local idx
	local webtimezone
	local timezone
	local mesh_role
	local mesh_support=$(uci -q get misc.features.supportMesh)
	if [ $mesh_support -eq 1 ]; then
		mesh_role=$(mesh_cmd role)
	else
		mesh_role="router"
	fi


	initted=`uci -q get xiaoqiang.common.INITTED`
	# "timezoneindex" exists indicates it was manually changed from web admin interface.
	# Apply the uci timezone config if timezoneindex exist.
	# Otherwise use timezone from country code.
	config_get idx "$cfg" timezoneindex
	config_get webtimezone "$cfg" webtimezone

	# check if index is in version 2 format
	v2_idx=$(echo ${idx} | grep -e ^2\.[0-9]*$ 2>/dev/null)

	#set timezone by CountryCode if not set by mannual and not inited
	if [ -z "$idx" -o "$initted" != "YES" ]; then
		set_timezone_from_countrycode $cfg
	else
		if [ "$mesh_role" != "RE" ] && [ -n "$v2_idx" -a -z "$webtimezone" ]; then
			# for version 2 index, webtimezone indicate it was mannual modified
			set_timezone_from_countrycode $cfg
		else
			config_get timezone "$cfg" timezone 'UTC'
			echo "$timezone" > /tmp/TZ
		fi
	fi
	# apply timezone to kernel
	hwclock -u -t
}


start() {
	config_load system
        config_foreach timezone_config system
}
